name: Build and Release JAR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: microsoft

    - name: Get project version
      run: |
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Project version: $version"
      id: get_version
      shell: sh
    
    
    

    - name: Build with Maven
      run: mvn clean package
   
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      id: create_release
      with:
        tag_name: v${{ steps.get_version.outputs.stdout }}
        release_name: v${{ steps.get_version.outputs.stdout }}
        draft: false
        prerelease: false

    - name: Release JAR
      uses: actions/upload-artifact@v2
      with:
        name: particle_life-jar-with-dependencies.jar
        path: target/particle_life-jar-with-dependencies.jar
